services:
    _defaults:
        public: true

    novanta.carriercontact.form.identifiable_object.builder.carrier_contact_form_builder:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
        factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
        arguments:
            - 'Novanta\CarrierContact\Form\Type\CarrierContactType'
            - '@novanta.carriercontact.form.identifiable_object.data_provider.carrier_contact_form_data_provider'
